### PR TITLE
fixed link extensions that are broken on website

### PR DESCRIPTION
**Pull request by jlbowm**
The main offender is the .html extensions from what I can tell.

### CODE REVIEW

**Comment by franciscojunior** [comment]
Thanks for the heads up!

**Comment by roji** [comment]
Hmm, I personally prefer having the .html extensions - this was previously working. Something appears to have changed with Github Pages/Jekyll , I'll try to take a look at some point.

**Comment by franciscojunior** [comment]
I remember it was working before too.

I also thought it could be something different with the page generator.

I merged it so we could have a non broken site until we see if we need to
make any other changes.
Em 31/03/2016 06:31, "Shay Rojansky" <notifications@github.com> escreveu:

**Comment by roji** [comment]
Sure, no problem. I'll try to take a look when I have a moment...

**Comment by roji** [comment]
FYI I fixed the original issue and the doc site now has .html extensions as before, this was apparently due to Github Pages upgrading to Jekyll 3 and us having a problematic permalink config.

**Pull request merged**
